import React, { useState } from 'react';
import QuotationForm from '../../components/quotation/QuotationForm';
import QuotationResult from '../../components/quotation/QuotationResult';
import { calculateQuotation } from '../../utils/calculateQuotation';
import api from '../../services/api';
import toast from 'react-hot-toast';

const AdminQuotationMaker = () => {
  const [result, setResult] = useState(null);
  const [customerData, setCustomerData] = useState(null);
  const [isLoading, setIsLoading] = useState(false);

  const onSubmit = async (data) => {
    setIsLoading(true);
    try {
      // Run frontend calculation
      const calculatedResult = calculateQuotation(
        parseFloat(data.monthlyBill),
        data.connectionType,
        data.state
      );
      
      const payload = {
        ...data,
        ...calculatedResult,
        status: 'Generated Internally' // Optional: mark as generated by admin
      };

      // Save to MongoDB via backend API
      await api.post('/quotations', payload);
      
      setResult(calculatedResult);
      setCustomerData(data);
      toast.success("Quotation generated successfully!");
      
    } catch (error) {
      toast.error("Failed to generate quotation. Please try again.");
      console.error(error);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <h2 className="text-3xl font-heading">Quotation Maker</h2>
      </div>
      
      <p className="text-gray mb-4">Generate instant calculations and PDFs for clients.</p>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Left Panel: Form */}
        <div className={result ? 'lg:col-span-7' : 'lg:col-span-8'}>
          <QuotationForm onSubmit={onSubmit} isLoading={isLoading} />
        </div>

        {/* Right Panel: Result */}
        {result && customerData && (
          <div className="lg:col-span-5">
            <QuotationResult result={result} customerData={customerData} />
          </div>
        )}
      </div>
    </div>
  );
};

export default AdminQuotationMaker;
